### ISSUE TITLE
如何增加产品翻译功能Chinese-cn

### ISSUE THREAD

**Issue by chinalujw** [kaneawk/WHMCS-CN-translations#5]
我们知道WHMCS内置了产品翻译功能，但并没有内置“Chinese-CN”语言选项，如何增加呢，谢谢。

https://help.whmcs.com/m/localisation/l/678185-translate-your-product-names-and-descriptions

**Comment by chinalujw** [comment]
> 我们知道WHMCS内置了产品翻译功能，但并没有内置“Chinese-CN”语言选项，如何增加呢，谢谢。
> 
> https://help.whmcs.com/m/localisation/l/678185-translate-your-product-names-and-descriptions

已经解决，使用“Chinese-CN”的中文文件名为 lang/chinese.php即可

**Comment by betaxab** [comment]
如果“常规设置-本地化”里默认语言是其它语言（例如英语），那么点产品名称什么的后面“翻译”按钮，它会显示 “Chinese-cn”条目。在这个条目里设置简体中文的描述就行。如下图所示：

![2020-11-24_10-43-17](https://user-images.githubusercontent.com/30405429/100040278-e71b2580-2e41-11eb-8749-654f0d260e3a.jpg)

如果“常规设置-本地化”里默认语言已经是简体中文（即“Chinese-cn”），那么点产品名称什么的后面“翻译”按钮，它不会显示 “Chinese-cn”条目。（难道你本地化里默认语言是简体中文默认的字段却写别的语言？？？没这样瞎搞的。）

### 不建议将 chinese-cn.php 重命名为 chinese.php，它会被自动更新覆盖掉，最后还原为默认自带的繁体中文。
